apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
        server_name foo.com.br;
        root /var/www;
        index index.html;
  
        location / {
            try_files $uri /index.html;
        }
    }
